### ISSUE TITLE
More generic examples needed

### ISSUE THREAD

**Issue by luminarious** [start-runner/start#25]
Hey! I was looking for Gulp alternatives and the pitch for this one is good, it looks very usable as far the API goes. It's currently very JS-centric though, so it would be great to have an example of how I would use this for more general build tasks (with Stylus or Sass to get CSS, Pug or Markdown to get HTML files).

Are this kind of examples planned?

**Comment by luminarious** [comment]
I'm pretty sure https://github.com/jescalan/accord could be used to simplify the preprocessing part as it already supports a ton of different languages.

**Comment by deepsweet** [comment]
Hey!

we already have [about 30 tasks](https://www.npmjs.com/browse/keyword/start-task) including [less](https://github.com/start-runner/less), [post-css](https://github.com/start-runner/postcss) and [clean-css](https://github.com/start-runner/clean-css). almost all of them were made by me for my personal needs :) but it's so easy to write a new task (imo much easier than with Gulp) so it's really community oriented. I can help anyone with anything if you provide me a real-life list of your needs, like sass, markdown, etc.

**Comment by tunnckoCore** [comment]
> I can help anyone with anything

Me too. 

@luminarious, i didn't see any more needs and problems when I started digging around `start`. In reality it is possible to combine them, because each task should/may return `file` object or `filepath` to the next task. In case with bundlers is a lil' bit different. That's why I opened https://github.com/tunnckoCore/start-rollup/issues/4  last hours.

I also created https://github.com/tunnckoCore/start-buble. :) And i'm thinking to create a task for the @jstransformers.

@deepsweet actually, I think we can move them here in that org :)

and a bit offtopic: i'm feeling cool that last days more and more stars (just noticed ~20 stars for last ~40 hours) and users come to `start` :) Maybe because the few links here and there :)

**Comment by deepsweet** [comment]
>I think we can move them here in that org

👍  please wait few more days before I'll finally finish tasks refactoring and bumping

>i'm feeling cool that last days more and more stars (just noticed ~20 stars for last ~40 hours) and users come to start :) Maybe because the few links here and there :)

seems like I have already seen only "here" but not "there". what is the other link? 😄  thanks for your help 🎉

**Comment by tunnckoCore** [comment]
> please wait few more days before

i'll try ;d;d can't sleep because the #bundlersHell (haha that hashtag.. huh)

> what is the other link?

HackerNews, /r/javascript and hashnode.com/n/nodejs

**Comment by deepsweet** [comment]
@luminarious so, do you need tasks for markdown or sass?

**Comment by luminarious** [comment]
My current projects use mostly Jade and Stylus, so I'd be very happy to try out tasks for these instead :)

**Comment by deepsweet** [comment]
I believe it's done.
