### ISSUE TITLE
A plugin for start

### ISSUE THREAD

**Issue by wcastand** [start-runner/start#4]
Hi, 
I don't really know how to put this.
So, i'm sorry if it's the wrong place :/

I develop a plugins for using Stylus with Start 
[start-stylus](https://www.npmjs.com/package/start-stylus)
[github](https://github.com/wcastand/start-stylus)
I would love to get your feedback if you discover some bugs or if i do some things wrong :)

Thank and i love Start !!

**Comment by deepsweet** [comment]
woohoo, first Start plugin made by someone else :+1: thanks for your interest.

It looks good. You can use [rest/spread properties](https://github.com/sebmarkbage/ecmascript-rest-spread) like `const options = { ...userOptions }` instead of `const options = Object.assign({}, userOptions)` because you are already using `stage-2` in your `.babelrc`. Also, you have to `log(file.path)` processed file path on promise resolving to indicate a progress, see [start-less](https://github.com/start-runner/less/blob/8312ab395047efdb24ab6f7dbc96337fa16d7bb2/lib/index.js#L30) for an example.
